# Generated by Django 2.2.6 on 2019-11-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('ID', models.IntegerField(primary_key='true', serialize=False)),
                ('Fname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('Add', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Zip', models.IntegerField(max_length=6)),
                ('Phone', models.IntegerField(max_length=6)),
                ('Text', models.CharField(max_length=200)),
                ('Data', models.CharField(max_length=200)),
            ],
        ),
    ]
