# Generated by Django 2.2.6 on 2019-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20191103_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='Data',
        ),
        migrations.RemoveField(
            model_name='database',
            name='ID',
        ),
        migrations.AddField(
            model_name='database',
            name='id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='database',
            name='Add',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='Country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='Email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='Fname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='Lname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='Phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='database',
            name='Text',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='Zip',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='database',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
